### ISSUE TITLE
Ambiguous error when supported language can not be found 

### ISSUE THREAD

**Issue by nellstephanj** [EntelectChallenge/2019-Worms#20]
When a starter bot has been added to the starter bot folder and the starter bot has been listed in the game-runner-config.json but not yet specified in the Java config an error occurs that does not clearly indicate the source of the problem.

We need to make it more clear that a new starter bot specification must be added to the BotRunnerFactory.java

**Comment by Mistborn94** [comment]
Great idea! I thought something similar when all of us were staring at that null pointer exception :)
