### ISSUE TITLE
Bug in command evaluation order

### ISSUE THREAD

**Issue by mdkozlowski** [EntelectChallenge/2019-Worms#30]
https://github.com/EntelectChallenge/2019-Worms/blob/012df1405eaa62e10407e688011dd21af0bcc79e/game-engine/src/commonMain/kotlin/za/co/entelect/challenge/game/engine/processor/WormsRoundProcessor.kt#L14-L19 If I'm understanding the above correctly, commands are sorted by their `order` property and then executed in that order.
The order values for [`TeleportCommand`](https://github.com/EntelectChallenge/2019-Worms/blob/012df1405eaa62e10407e688011dd21af0bcc79e/game-engine/src/commonMain/kotlin/za/co/entelect/challenge/game/engine/command/implementation/TeleportCommand.kt#L14) and [`DigCommand`](https://github.com/EntelectChallenge/2019-Worms/blob/012df1405eaa62e10407e688011dd21af0bcc79e/game-engine/src/commonMain/kotlin/za/co/entelect/challenge/game/engine/command/implementation/DigCommand.kt#L17) are 2 and 1 respectively, so dig commands will be sorted before move commands
But in [the documentation](https://github.com/EntelectChallenge/2019-Worms/blob/012df1405eaa62e10407e688011dd21af0bcc79e/game-engine/game-rules.md#command-order) it's written that move commands should be executed before dig commands

**Comment by Mistborn94** [comment]
Nice catch! I will try to get this resolved before the next starter pack release.  I do not believe this will have a major impact as the command validation should still catch the rules for moving into cells that are also being digged into.
