### ISSUE TITLE
Friendly kills should not provide positive score points

### ISSUE THREAD

**Issue by Blaarkies** [EntelectChallenge/2019-Worms#42]
https://forum.entelect.co.za/t/undefined-behaviour/717/4

Killing your own own will currently give you +40 points. This means to optimize score, you should "deny" your own worms right before the opponent kills them. This is worms, not DOTA 😂

**Comment by Mistborn94** [comment]
As part of this we also need to reword the readme to make it clear that you get only 40 points for killing an enemy worm, not 20 + 40 = 60
