### ISSUE TITLE
Add all players' last command to the state files

### ISSUE THREAD

**Issue by Blaarkies** [EntelectChallenge/2019-Worms#44]
https://forum.entelect.co.za/t/see-opponents-last-move/728

Add field `lastCommand: ['C;42;move 4 9']` to json/text state files.

**Comment by rsheasby** [comment]
Just a comment that implementation of this feature should probably include what the opponent's last active worm was. Otherwise it requires the players to figure it out by taking the current worm ID, figuring out what worms were alive last round, etc...

**Comment by warren-sentient** [comment]
Is this still being implemented?

**Comment by Blaarkies** [comment]
We are currently focused on finishing up the university-cup challenge, but we will re-evaluate this soon after 😄

**Comment by Quiescent** [comment]
Hi all.

I've just created https://github.com/EntelectChallenge/2019-Worms/pull/73 to address this issue.
It does so by simply looking at the command feedback and printing the move made by the first opponent in the list for that round and since we only ever have matches between two players it should be correct to do so.

WDYT?

**Comment by Quiescent** [comment]
Thanks @Blaarkies and @Mistborn94 for the support in getting https://github.com/EntelectChallenge/2019-Worms/pull/73 merged!
Can we close this issue now?

**Comment by Blaarkies** [comment]
Thanks a lot for taking lead on this one, we are glad to help 😄 
I believe if you add `fix #73` in the description of a pull request, it would auto close the issue? no worries 😋

**Comment by Quiescent** [comment]
Ahh!  I was wondering how to link the two.  Thanks :)
A cursory search of the docs didn't reveal the solution.
