### ISSUE TITLE
C++ bot doesn't have debug.cpp mentioned in README

### ISSUE THREAD

**Issue by robjermy** [EntelectChallenge/2019-Worms#45]
Hi, the readme for the C++ bot mentions a debug.cpp. However it doesn't seem to be in that folder.

**Comment by DigitumDei** [comment]
Sorry, I think I was pruning down the code for the original submission that got deleted. Probably should just remove that from the readme, all it contained was a windows specific MessageBox call to make it easier to attach a debugger at certain parts of the code.

**Comment by robjermy** [comment]
Oh I see. Thanks. I'm not sure if this is a valid place to ask this next question but how can I actually debug my C++ bot. I have added my own debugger waiting code and am trying to use GDB to attach to the java process, however I'm not able to attach to my bot

**Comment by DigitumDei** [comment]
I've only been debugging with Visual Studio, so not sure of the specifics of connecting with GDB. But you would have to connect to the cppbot.exe generated, not the java process. 

Additionally almost all of my debugging happens outside of the botrunner. I run though a match with the bot runner, and then open up cppbot.exe in the folder it runs in, attach the debugger and then just type the round I want to debug. Assuming you run it where the bot runner runs it, the round files are all there, and you can debug specific rounds, or the same round multiple time etc.
