### ISSUE TITLE
Python starter-bot AttributeError line 133

### ISSUE THREAD

**Issue by MarthinusBosman** [EntelectChallenge/2019-Worms#49]
The python starter-bot experienced an error during late game on line 133:
`cell_type = self.get_cell_type(cell.x, cell.y)`

Throwing error:
`AttributeError: 'numpy.ndarray' object has no attribute 'x'`

it was easily fixed by changing the line to:
`cell_type = self.get_cell_type(cell[0], cell[1])`

**Comment by Mistborn94** [comment]
Hi @MarthinusBosman 

Thank you for the report,  the team will investigate and address this issue. If you want to speed up the process, please consider submitting a pull request.
