### ISSUE TITLE
Friendly fire leads to killshot score deduction later on

### ISSUE THREAD

**Issue by bawalsh** [EntelectChallenge/2019-Worms#72]
When a worm accidentally shoots a friendly worm, and later on in the game that worm gets killed by the opponent, `+40` is awarded to the opponent **but `-40` is deducted from the friendly player as well.**

The `setScoresForKilledWorms` function in `WormsMap.kt` should probably take the round of the shot into account, to determine which player shot the worm last. It looks like it is iterating through both players in `lastAttackedBy`, irrespective of who gave the killshot.

**Comment by Blaarkies** [comment]
Did this happen in 1 single round?

In a single round, there is no sequence of who shoots first, both shooting effect occur at exactly the same time. So both players are responsible for the killshot.

If this happened over 2 or more rounds, then there is definitely a problem, since all worms have `worm.lastAttackedBy.clear()` called on them after their killshot score is determined.

Is this correct?

**Comment by bawalsh** [comment]
It happened over multiple rounds.

**Example:**
In round 46 Player A accidentally shoots their own worm. `takeDamage` in `Worm.kt` adds Player A to `lastAttackedBy` for that worm.

Later on in round 248 Player B shoots that same worm and kills it. Again `takeDamage` in `Worm.kt` is triggered, and Player B gets added to `lastAttackedBy` for that worm.

Now `setScoresForKilledWorms` in `WormsMap.kt` executes. `.distinct()` is called on `lastAttackedBy`, leaving two items: Player A and Player B. For Player A `config.scores.killShot` is deducted, and for Player B `config.scores.killShot` is added.

**Comment by Blaarkies** [comment]
@bawalsh 
Thanks a lot for the investigation on this one, this was quite easy to fix after you put in all the hard work 😉 
I added a [test case](https://github.com/EntelectChallenge/2019-Worms/pull/74/files) to validate this behavior, do you mind giving it a quick to if we missed something?
