### ISSUE TITLE
Worms killed by lava still dig/shoot/w/e

### ISSUE THREAD

**Issue by Quiescent** [EntelectChallenge/2019-Worms#78]
In the code:
```kotlin
fun processRound(wormsMap: WormsMap, wormsCommands: Map<WormsPlayer, List<WormsCommand>>): Boolean {
        logger.info { "Processing round: Round=${wormsMap.currentRound}" }

        logger.info { "Progressing BattleRoyale" }
        wormsMap.progressBattleRoyale(config)

        logger.info { "Ticking worm frozen timers" }
        wormsMap.tickFrozenTimers()

        val mutableCommandsMap = wormsCommands.toMutableMap()
        executeSelectCommands(mutableCommandsMap, wormsMap)
        executeOtherCommands(mutableCommandsMap, wormsMap)

        logger.info { "Updating player's active worms" }
        for (player in wormsMap.livingPlayers) {
            player.selectNextWorm()
        }

        logger.info { "Applying powerups" }
        wormsMap.applyHealthPacks()

        logger.info { "Adding kill scores for dead worms" }
        wormsMap.setScoresForKilledWorms(config)

        logger.info { "Removing dead worms from the map" }
        wormsMap.removeDeadWorms()

        logger.info { "Checking for referee issues" }
        wormsMap.detectRefereeIssues()

        return true
    }
```

We deal out lava damage and then execute worm commands anyway.  If a worm dies due to lava damage it will still execute it's commands.  This means that a dead worm on lava can in theory still: shoot, dig etc.

In my testing I've only seen it *dig from beyond the grave(!)*

A cursory glance at the commands reveals that this might also be the case for shooting after having been blasted to death by the banana bomb -- have I missed something?

It seems that the solution would be to check whether the current worm is alive inside of each command or something to that effect.

**Comment by Mistborn94** [comment]
Hi @Quiescent

This is expected behaviour. Our command execution works within the following rules:
1. Any move that was valid at the beginning of the round, is still valid at execution time
2. We simulate commands as if they all happen at the same time

The only situations where command order really matters is in how movement interacts with the other commands: Worms can move into or out of range of another worm's attack. 

Think of it as the final act of a dying worm :)

**Comment by Quiescent** [comment]
Hi @Mistborn94,

Thanks for the reply and noted.

Just to explain where I was coming from, because I think that this kind of subtlety deserves explicit mentioning in the rules:
Some of the commands do have precedence which matters (as you mentioned).
You can dig out a square and have your opponent shoot you or you could deny a square which would have awarded points for banana bombing by digging it out.

Death is a special case which I haven't spotted being mentioned (did I miss something?)
I can put something together for the rules to that effect if you like?

**Comment by Mistborn94** [comment]
Hi @Quiescent 

You are welcome to submit a pull request to update the rules, I think that is a great idea.

**Comment by Quiescent** [comment]
Hi @Mistborn94,

Thanks.
However, I see that the rule is already clarified in https://github.com/EntelectChallenge/2019-Worms/compare/feature/3-1-balance-tweaks
So I'll just leave it to that branch to make the rule clear :)
