### ISSUE TITLE
Incorrect worm selected

### ISSUE THREAD

**Issue by Quiescent** [EntelectChallenge/2019-Worms#84]
Hi all.  I think that I've found a bug in the game engine.

Scenario:
- Player two has worms 1, 2 and 3 alive.
- It is currently worm 2's turn for player 2.
- Player two and player one make non-select moves.

Outcome: 
- Player two's current worm after the turn is complete becomes 1.

Expectation:
- I would have expected it to be worm 3's turn for player 2.

Investigation:
I've attached the global state and the state from both players perspective (I had to change the extensions to "txt" in order for Github to accept them).  All of it seems wrong.  The global state goes from worm 1 to 3 and the player state goes from 2 to 1(!?)

This bug has serious consequences to the correctness of any algorithm which predicts a few moves into the future.  Please can it be fixed as a matter of urgency.

[GlobalState-round-160.txt](https://github.com/EntelectChallenge/2019-Worms/files/3558589/GlobalState-round-160.txt)
[GlobalState-round-161.txt](https://github.com/EntelectChallenge/2019-Worms/files/3558590/GlobalState-round-161.txt)
[Player-1-state-round-160.txt](https://github.com/EntelectChallenge/2019-Worms/files/3558592/Player-1-state-round-160.txt)
[Player-1-state-round-161.txt](https://github.com/EntelectChallenge/2019-Worms/files/3558593/Player-1-state-round-161.txt)
[Player-2-state-round-160.txt](https://github.com/EntelectChallenge/2019-Worms/files/3558594/Player-2-state-round-160.txt)
[Player-2-state-round-161.txt](https://github.com/EntelectChallenge/2019-Worms/files/3558595/Player-2-state-round-161.txt)

System information:
 - NixOs 18
 - Running game engine built from develop.
(Not sure what else is relevant.  Please let me know if you need any more information.)

**Comment by Mistborn94** [comment]
The difference between the global state and the player state is because player state is written at the beginning of the round while global state is written at the end of the round. This might not have been indicated clearly  since the global state was primarily intended for visualizers. 

However, if I understand your post correctly that is not the only issue. We will investigate this.

**Comment by Quiescent** [comment]
Thanks for clarifying @Mistborn94 and yes, your understanding is correct.  There does appear to be another problem here.

**Comment by Mistborn94** [comment]
I think I have this one pinned down: The issue occurs specifically when the current worm dies during the round. A fix should be implemented early next week.

**Comment by Quiescent** [comment]
Thanks for getting to the bottom of this!  :+1:
